name: filtertest

on:
  pull_request:

# hack for https://github.com/actions/cache/issues/810#issuecomment-1222550359
#env:
#  SEGMENT_DOWNLOAD_TIMEOUT_MIN: 3

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be formatted as JSON array
        list-files: json
    
        # In this example all changed files are passed to the following action to do
        # some custom processing.
        filters: |
          changed:
            - '**'
    - name: Lint Markdown
      run: |
        cat steps.filter.outputs.changed_files
